
var Cookie={get:function(name){var value='',matchs;if(matchs=document.cookie.match("(?:^| )"+name+"(?:(?:=([^;]*))|;|$)"))value=matchs[1]?unescape(matchs[1]):"";return value},set:function(name,value,expire,domain){expire=expire||30*24*3600*1000;var date=new Date(),cookie="";date.setTime(date.getTime()+expire);cookie=name+"="+escape(value)+";expires="+date.toGMTString()+";path=/;";domain&&(cookie+="domain="+domain+";");document.cookie=cookie},del:function(name,domain){Cookie.set(name,'',-1,domain)}};function setCookie(cooktval){var Days=1;var exp=new Date();exp.setTime(exp.getTime()+Days*24*60*60*1000);document.cookie=cooktval+"=yes;expires="+exp.toGMTString()}
if(typeof(page)=="undefined"){page="0"};function addwdjbtn(){console.log("进入豌豆荚判断")
var apkurl=$(".down-btn a.i-az").attr("href");var bmname=info.package;if(bmname==""){console.log($(".g-app-cont h1").html())
bmname=$(".g-app-cont h1").html();}
function addhref(stype){if(stype=="1"){$(".down-btn a.i-az").attr("href",apkurl);}else{$(".down-btn a.i-az").attr("href",'JavaScript:void(0)');$("#g-uwdj").click(function(){if($(this).hasClass("uno")){$(this).removeClass("uno");$(".down-btn a.i-az").text("立即下载");$(".down-btn a.i-az").attr("href",apkurl);}else{$(this).addClass("uno");$(".down-btn a.i-az").text("高速下载");$(".down-btn a.i-az").attr("href",'JavaScript:void(0)');}});}}
wandoujiaready();$("#address").on("click",function(){if($('#g-uwdj').hasClass("uno")){waidoujiahandle();}else{addhref(1);}})
function wandoujiaready(){WdjBZ.init({packageName:bmname,channel:'pm_nubz_ssk',downloadUrl:apkurl,});WdjBZ.checkPackageName(function(ret){if(!ret.code){$(".f-down-cont").prepend('<p id="g-uwdj" class="uno">使用豌豆荚助手</p>');$(".down-btn").append('<p class="g-stips">需先下载豌豆荚助手,使用高速下载更快更安全</p>');$(".down-btn a.i-az").text("高速下载");console.log('WdjBZ.checkPackageName ok.');addhref(2);}else{addhref(1);$(".down-btn a.i-az").text("立即下载");console.log('WdjBZ.checkPackageName failed.');$('#g-uwdj').attr('class','');}});}
function waidoujiahandle(){WdjBZ.downloadFast(function(ret){if(!ret.code){console.log('WdjBZ.downloadFast ok.');}});}}
$(function(){$("#bdcs-search-form-input").on('change',function(){var inputtxt=$(this).val();$("#bdcs-search-form-submit").click(function(){$(this).attr('href','https://m.baidu.com/s?word='+inputtxt+'&ssid=7021c7b3d2e4353538c154&si=m.shuoshuokong.com');});});var mentext=$(".article-list-btns a").eq(1).attr("href");var durl=window.location.href;$(".g-cnot-bg nav a").each(function(){var navurl=$(this).attr("href");var menturl=$(this).text();if(durl.indexOf(navurl)!=-1){$(this).addClass("hover");}
if(durl==navurl){$(this).addClass("hover");}})
$("body").append("<a href=\"javascript:;\" class=\"m-backTop\"></a>");$(window).scroll(function(){if($(window).scrollTop()>=300){$(".m-backTop").show();}else if($(window).scrollTop()<300){$(".m-backTop").hide()}});$(".m-backTop").click(function(){$('body,html').animate({scrollTop:0},1000);return false;});$("#mcate").click(function(){$("#mcateCont").toggleClass("u-block");}),$("#mcateCont p span").click(function(){$(this).addClass("cur").siblings().removeClass("cur");var e=$("#mcateCont p span").index(this);$("#mcateCont ul").eq(e).addClass("on").siblings().removeClass("on")}),$("#topNav").length>0&&e("#topNav ul");var o=document.domain,i=document.referrer;i.indexOf(o)>-1&&window.history.length>0&&$(".sback, .back").on("click",function(){return window.history.go(-1),!1})
var contimg=$("#content li").height();$(".screenshot").height(contimg);$(".zt a:nth-child(8n)").after('<b></b>');if($("#details").height()<=700){$("#expand").hide();$("#details").height("auto")}else{$("#details").height(700);$(".lookmore").addClass("on-hover");$("#expand span").click(function(){if($("#expand span em").text()=="ทุกสิ่งช่างกว้างใหญ่ไพศาล"){$("#details").height("auto");$("#expand span em").text("no");$("#expand span").addClass("m-click-bg");$(".lookmore").removeClass("on-hover");}else{$("#details").height("700px");$("#expand span em").text("展开全部内容");$("#expand span").removeClass("m-click-bg");$(".lookmore").addClass("on-hover");}})}
$(".f-search-ico").click(function(){if($(".g-search-box").css('display')==='none'){$(".g-search-box").show()}else{$(".g-search-box").hide()}})
$(".g-search-box").hover(function(){$(this).show();},function(){$(this).hide();});$("content").on("touchstart",function(){$(".g-search-box").hide();});if(page==1)
{$(".g-rank-bd .g-rank-ul").eq(0).addClass("block");$(".g-hotsy .g-hotsy-ul").eq(0).addClass("block");$(".f-hot-a a").click(function(){$(this).addClass("m-hover").siblings().removeClass("m-hover");var contul=$(".f-hot-a a").index(this);$(".g-hotsy .g-hotsy-ul").eq(contul).addClass("block").siblings().removeClass("block")});$(".f-rank-link a").click(function(){$(this).addClass("m-hover").siblings().removeClass("m-hover");var contul=$(".f-rank-link a").index(this);$(".g-rank-bd .g-rank-ul").eq(contul).addClass("block").siblings().removeClass("block")});var tags_a=$(".label-box a");tags_a.each(function(){var x=9;var y=0;var rand=parseInt(Math.random()*(x-y+1)+y);$(this).addClass("tags"+rand);});}
var tit=$(".jogger").children("a:eq(0)").attr('title')
if(tit=='Total record'){$(".jogger").children("a:eq(0)").hide();}
var lastname=$(".jogger a:last").text();if(lastname=='尾页'){$(".jogger a:last").hide();}
if(page==3){var isSwbUrl=false;var downHref=$("#address").attr("href");var pbsbwNew=["tj.chenjianxiang.com","guopan.cn","9game.cn","tj.viphxw.com","kepan365.com","99maiyou.com","sp4.tools86.com"];for(i=0;i<pbsbwNew.length;i++){if(downHref.indexOf(pbsbwNew[i])>-1){isSwbUrl=true;}}
rem();window.onresize=function(){rem();}
function rem(){var w=document.documentElement.offsetWidth;document.documentElement.style.fontSize=w/7.2+'px';window.onresize=function(){var w=document.documentElement.offsetWidth;document.documentElement.style.fontSize=w/7.2+'px';}}
addLldown("#details");function addLldown(obj){$(obj).after('<a href="http://tj.viphxw.com/e/23/001/121205" style="width:100%; height:1.91rem; background:url(/skin/new2018/images/llhz-down.jpg) no-repeat; background-size:7.2rem; display:block; overflow:hidden; position:relative;"><strong style="width: 4.2rem; height: auto; line-height: .38rem; font-size: .3rem; font-weight: bold; color: #f6e9c6; padding: 0 0 0 .56rem; margin: 1rem 0 0; display: block; overflow: hidden; opacity: .98;">下载'+$("h1").text()+'</strong></a>');};var tags=$(".xgk-cont").html();var tagstxt=tags.replace("标签：","")
$(".g-xgk").append(tagstxt);$(".g-xgk span").remove();var touimgnum=$("#content img").length;var imgurl=''
if(touimgnum>1){$("#content img").each(function(i){imgurl=$(this).attr("src")
var imgurt=imgurl.split("!")[0]
$(this).attr("data-original",imgurt);$(this).wrap('<em class="s-img"><a href="'+imgurt+'" class="swipebox"></a></em>')});$('.s-img').swipebox();$(".m-she").hide();$("#swipebox-download").css("margin-left","-50px")}
var dnav=167;$(".f-ctab li").click(function(){var n=$(this).index();if(n<3){var gotoTop=$(".f-tabs-bd").eq(n).offset().top-dnav;$("body,html").animate({scrollTop:gotoTop},500)}else{var gotoTop=$("#down-mian").offset().top-dnav;$("body,html").animate({scrollTop:gotoTop},500)}})
if(/iphone|ipad/i.test(navigator.userAgent)){var iosurl=iosdown.url;$(".down-btn a").attr('href',iosurl);if(iosurl==""){$("#address").text("暂无下载").css({"background":"#8e8e8e","color":"#fff"}).attr("href","javascript:;")}}else{var azurl=$(".i-az").attr('href');if(azurl==""){$("#address").text("暂无下载").css({"background":"#8e8e8e","color":"#fff"}).attr("href","javascript:;")}}
var zthj=$(".g-zthj a").length;if(zthj<=0){$(".g-zthj-cont").hide();}
var xgbb=$(".g-xgbb ul li").length;if(xgbb<=0){$(".g-xgbb").hide();}
if(typeof(info)=="undefined"){info="0"};var pbaz=$(".down-btn a.i-az").attr("href");var qpUrl='tt.wang6g.com';if(pbaz.indexOf(qpUrl)!=-1){$(".down-btn a.i-az").addClass("no-down");$(".down-btn a.i-az").text("资源已下架");$(".down-btn a.i-az").attr("href","javascript:void(0);");}
var rid=info.classid;var noswburl=$(".down-btn a.i-az").attr("href");var isads="false";var pbsbw=["tj.chenjianxiang.com","sp.ulxue.com","sp2.vaatn.com","download.jiuyao666.com","ugame.9game.cn","tj.qqtj99.com","apk.dian5.com","down.tuanyx.co","sp.apk17.com","tu.apk17.com","sp2.ftaem.cn","sp.ulxue.com","down.520cai.net","downlhh.btgame99.com","fb.3733.com","cps.99maiyou","and.milu.com","down2.guopan.cn","tg.kepan365.com","downlhh.btgame99.com","down.5wbt.com","sy.qqtn.com","uri.cgamex.com","download.277sy.com","www.i6h5.com","kk.tingxz.com","xzsp3.zhanyu55.com","tt.wang6g.com","xzsp.9pj8m.com","ydb.vaatn.com","xzsp3.zhanyu55.com","sp2.ftaem.cn","chenjianxiang.com","cyhy8.com","eoemarket.com","haowanyou.com","112wan.com","paojiao.cn","jiyw.com","66shouyou.com","downfx2.cmge.com","unionsy.com","phzdownload.gllkgame.com","hsxizhi.com","dlsutong.cn","602.com","ind9ed.com","63yx.com","6513.com","yileyoo.com","kingcheergame.com","gzjykj.com","songshugame.cn","myx916.com","ksyun.com","xmwan.com","fire2333.com","aliyuncs.com","youdiancx.com","myqcloud.com","yixin.im","yx.127.net","163.com","uri6.com","nikkigames.cn","papa91.com","84fk.com","dovoscape.com","108jz.com","693975.com","niuboli.com","tanwan.com","twanxi.com","huangxiu1.com","jjyx.com","guaishou66.com","duoyi.com","3737.com","leishengame.com","shangshiwl.com","aoingame.com","faxianapk.com","6xwan.com","7gwan.com","youximao.com","zwyouxi.com","happyelements.cn","qiyutianxia.com","yingxiong.com","play800.cn","tpxl.com","xiaodiyouxi.com","bamenzhushou.com","youximax.com","duomiwan.com","66bay.com","btgame99.com","xxzhushou.cn","dongyouxi666.com","277sy.com","wpscdn.cn","inmome.com","185sy.com","anfeng.com","tuanyx.com","game-center.cn","milu.com","xyzs.com","3733.com","kepan365.com","233xyx.com","tj.viphxw.com","xzsp3.nevehicle.cn","xzp10.lzljzky.com","sp16.850671.com","sp4.tools86.com","sp10.down5g.net","sp4.lzljzky.com"];var pburl="kk.tingxz.com";var swburl="sp.ulxue.com";if(!/iphone|ipad/i.test(navigator.userAgent)){if(noswburl.indexOf(swburl)==-1){if(noswburl.indexOf(pburl)!=-1){$(".down-btn a.i-az").addClass("no-down");$(".down-btn a.i-az").text("暂无下载");$(".down-btn a.i-az").attr("href","javascript:void(0);");}else{isads="true";for(var i=0;i<pbsbw.length;i++){if(noswburl.indexOf(pbsbw[i])!=-1){isads="false";}}}}else{if(rid=="50"){$(".down-btn a.i-az").addClass("no-down");$(".down-btn a.i-az").text("资源已下架");$(".down-btn a.i-az").attr("href","javascript:void(0);");}}
var dkswb='tj.viphxw.com';var Uurl=noswburl.lastIndexOf("\/");var daikuanURL=noswburl.substring(Uurl+1,noswburl.indexOf("?"));if(noswburl.indexOf(dkswb)!=-1&&daikuanURL=='37246'){$(".down-btn a.i-az").addClass("no-down");$(".down-btn a.i-az").text("暂无下载");$(".down-btn a.i-az").attr("href","javascript:void(0);");}}
if(isads=="true"){if(info.pcstar!='1'&&info.soft!="\u4e0b\u67b6"){if(typeof(info.package)!='undefined'){}}}
$(document).ready(function(){var navTop=$(".f-down-cont").height()+250;var downtxt=$(".down-btn a.i-az").text();var dqxzdz=$(".down-btn a.i-az").attr("href");$(window).scroll(function(){if($(window).scrollTop()>navTop){$(".f-down-cont").addClass("f-float");if($('#g-uwdj').hasClass("uno")){$(".down-btn a.i-az").attr("href",dqxzdz).text("立即下载");}}else{$(".f-down-cont").removeClass("f-float");if($('#g-uwdj').hasClass("uno")){$(".down-btn a.i-az").attr("href","JavaScript:void(0)").text("高速下载");}}})})
var titleName=$(".g-app-cont h1").text();if(titleName.indexOf('快手')!==-1){zsisAds=true;}
var openurl=document.referrer.substr(0,20);var cityAr=['北京','武汉']
var zscity=['北京']
$.ajax({async:true,url:"//api.map.baidu.com/location/ip?ak=TgwAfmHofaIoqDl4zQynNdchcmyrI9uc",type:"get",dataType:"jsonp",jsonp:'callback',jsonpCallback:'city',data:{q:"javascript",count:1},success:function(response,status,xhr){var province=response.address.split('|')[1];var city=response.address.split('|')[2];if($.inArray(city,cityAr)!=-1){if(typeof(info)!="undefined"){if(typeof(info.soft)!='undefined'){if(info.soft=="\u4e0b\u67b6"){$(".down-btn a.i-az").addClass("no-down");$(".down-btn a.i-az").text("资源已下架");$(".down-btn a.i-az").attr("href","javascript:void(0);");}}
if(typeof(info.pcstar)!='undefined'){if(info.soft!="\u4e0b\u67b6"){if(info.pcstar=='1'){console.log(info.pcstar)
$(".down-btn a.i-az").addClass("no-down");$(".down-btn a.i-az").text("资源已下架");$(".down-btn a.i-az").attr("href","javascript:void(0);");}}}}}},error:function(){}});if(/android/i.test(navigator.userAgent)){var onehtml='<div class="g-applist allbox"><a href="http://tj.viphxw.com/e/23/22/78199?soft_id=34024"><i><img src="http://pic.shuoshuokong.com/d/file/2019-09/1379706785d618b1d07e843528207915.png" alt="每天赚100元的软件v2019"></i><p>每天赚100元的软件</p></a><a href="http://tj.viphxw.com/e/23/22/78199?soft_id=36118"><i><img src="http://pic.shuoshuokong.com/d/file/2019-10/861e2b97812f27a1f3eadfe42cbfc3e4.png" alt="一元提现秒到账的appv2019"></i><p>一元提现秒到账的app</p></a><a href="/youxi/29785.html"><i><img src="http://pic.shuoshuokong.com/d/file/2020-04/ee052821e4765bb3245c7296a95b5e0f.png" alt="口袋觉醒v2.1.0.26233"></i><p>口袋觉醒</p></a><a href="/youxi/5339.html"><i><img src="http://pic.shuoshuokong.com/d/file/2019-06/2be64b892ba2663a4779d50cbf47208f.png" alt="姚记捕鱼万元奖v1.0.4.0.0"></i><p>姚记捕鱼万元奖</p></a><a href="/youxi/11263.html"><i><img src="http://pic.shuoshuokong.com/d/file/2019-03/354cf8a8717d691674a2622db211c438.png" alt="皇帝养成计划v1.1.0.00630009"></i><p>皇帝养成计划</p></a><a href="/youxi/28963.html"><i><img src="http://pic.shuoshuokong.com/d/file/2020-03/ea3fa30fa6d8b253db40d0f0e344c4e5.gif" alt="三国志战略版v2004"></i><p>三国志战略版</p></a><a href="/youxi/2473.html"><i><img src="http://pic.shuoshuokong.com/d/file/2019-10/352172bcbd8dd2a8d9d4fec0499f306f.png" alt="一起来跳舞v3.9.12"></i><p>一起来跳舞</p></a><a href="/youxi/8.html"><i><img src="http://pic.shuoshuokong.com/d/file/2020-06/d20f188b75433fc46df2a6c426b29bed.png" alt="迷你世界v0.45.0"></i><p>迷你世界</p></a></div>';$(".g-xgbb").before(onehtml);}}
var conHeight=$(".g-key-font .box").height();var i=0;setTimer=setTimeout(function(){window.setInterval(function(){i++;if(i<=conHeight){$(".g-key-font .box").animate({top:-i},0)}else{i=0;$(".g-key-font .box").animate({top:-i},0)}},50)},3000)
$("#g-look-desc").click(function(){$("body").append("<div class=\"txthtml\"></div>");var txthtml=$(".g-key-font").html();$(".txthtml").prepend(txthtml);$(".txthtml").append("<b id=\"m-close-desc\">关闭</b>");$("body").append("<b id=\"m-alert-bg\"></b>");$("#m-close-desc").click(function(){$(".txthtml").remove();$("#m-alert-bg").remove();})});var knum=8;$('.g-zthj-list').each(function(i){var klihei=$('.g-zthj-cont').find('.on li').height()+26;var klinum=$(this).find('ul li').length;if(klinum<(knum+1)){$(this).find('.f-more-zt').remove();}else{$(this).find('ul').height(klihei*knum);}});$('.f-more-zt').click(function(){var klihei=$('.g-zthj-cont').find('.on li').height()+26;console.log(klihei)
var kdhei=$(this).prev('.g-zthj-list ul').height();var kdnum=$(this).prev('.g-zthj-list ul').find('li').length;if((kdhei+(knum*klihei))<=(klihei*kdnum)){$(this).prev('.g-zthj-list ul').height(kdhei+(knum*klihei));}else{$(this).prev('.g-zthj-list ul').height(klihei*kdnum);$(this).text('暂无更多内容');}});$(".f-zt-a a").click(function(){$(this).addClass("m-hover").siblings().removeClass("m-hover");var contul=$(".f-zt-a a").index(this);$(".g-zthj-cont .g-zthj-list").eq(contul).addClass("on").siblings().removeClass("on")});if(page=='so')
{var key=soname.key;console.log(key)
var notitle=['彩票','彩','棋牌'];var notishi='<div class="f-nr" style="display:none; width:100%;height:120px;line-height:120px;text-align: center;background-color: #fff; font-size: 20px; color: #34d0ba; margin:20px auto">该搜索内容已经下架，请看看其他内容吧。</div>';$('.g-cnot-bg').after(notishi);for(p=0;p<notitle.length;p++){if(key.indexOf(notitle[p])!=-1){$(".article-list-btns ,.g-listul").remove();$(".f-nr").show();}}}});